# Generated by Django 4.1.7 on 2023-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Duration', models.CharField(max_length=30)),
                ('AutherName', models.CharField(max_length=100)),
            ],
        ),
    ]
